version: 3

services:
    frontend:
      build: ./frontend
      network_mode: host
      ports:
        - "4000:4000"

    backend:
      build: ./backend
      network_mode: host
      ports:
        - "8080:8080"

    ml:
      build: ./ml
      network_mode: host

    db:
      build: ./db
      network_mode: host
      ports:
        - "5432:5432"